name: aweytak
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.2.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/steps_cpr_adult.json
    - assets/steps_cpr_child.json
    - assets/steps_cpr_infant.json
    - assets/steps_cpr_choking.json
    - assets/steps_cpr_unconscious.json
    - assets/steps_bleed_nose.json
    - assets/steps_bleed_deepcut.json
    - assets/steps_bleed_minor.json
    - assets/steps_bleed_severe.json
    - assets/steps_bleed_internal.json
    - assets/steps_burn_mild.json
    - assets/steps_burn_severe.json
    - assets/steps_burn_chemical.json
    - assets/steps_burn_electrical.json
    - assets/steps_burn_sun.json
    - assets/steps_choking_adult.json
    - assets/steps_choking_child.json
    - assets/steps_choking_infant.json
    - assets/steps_choking_unconscious.json
    - assets/steps_choking_severe.json
    - assets/steps_fever_high.json
    - assets/steps_fever_low.json
    - assets/steps_seizure_generalized.json
    - assets/steps_seizure_febrile.json
    - assets/steps_seizure_status_epilepticus.json
    - assets/steps_snake_bite.json
    - assets/steps_insect_sting.json
    - assets/steps_scorpion_sting.json
    - assets/steps_spider_bite.json
    - assets/steps_bee_sting.json
    - assets/steps_fainting.json
    - assets/steps_shock.json
    - assets/steps_heat_exhaustion.json
    - assets/steps_hypovolemic_shock.json
    - assets/steps_anaphylactic_shock.json
    - assets/steps_malaria.json
    - assets/steps_cholera.json
    - assets/steps_hepatitis.json
    - assets/steps_tb.json
    - assets/steps_diarrhea.json
    - assets/steps_typhoid.json
    - assets/steps_measles.json
    - assets/steps_dengue.json
    - assets/steps_diabetes.json
    - assets/steps_asthma.json

  uses-material-design: true

