name: aweytak
description: "A First Aid app."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Widened SDK constraint to allow for newer dependencies

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0 # Ensure this is updated as per previous step
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.0 # Ensure this is present and updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Updated to latest major version
  hive_generator: ^2.0.1
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4 # Updated to latest major version

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/scenarios/
