name: aweytak
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.2.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/steps_cpr_adult.json
    - assets/steps_cpr_child.json
    - assets/steps_cpr_infant.json
    - assets/steps_cpr_choking.json
    - assets/steps_cpr_unconscious.json
    - assets/steps_bleed_nose.json
    - assets/steps_bleed_deepcut.json
    - assets/steps_bleed_minor.json
    - assets/steps_bleed_severe.json
    - assets/steps_bleed_internal.json
    - assets/steps_burn_mild.json
    - assets/steps_diabetes_emergency.json
    - assets/steps_asthma_attack.json

  uses-material-design: true

